services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - nginx_certs:/etc/nginx/ssl
    networks:
      - app-network
    env_file:
      - .env
    restart: always
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wp_data:/var/www/wordpress
    env_file:
      - .env
    networks:
      - app-network
    restart: always
    depends_on:
      - mariadb  # You'll add this later

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - wp_db_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/agarbacz/data/wordpress

  wp_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/agarbacz/data/mariadb

  nginx_certs:
    driver: local


networks:
  app-network:
    driver: bridge