CREATE DATABASE IF NOT EXISTS wordpress_db;

CREATE USER IF NOT EXISTS 'wp_user'@'%' IDENTIFIED BY '42';
GRANT ALL PRIVILEGES ON wordpress_db.* TO 'wp_user'@'%';

CREATE USER IF NOT EXISTS 'site_owner'@'%' IDENTIFIED BY 'secure42';
GRANT ALL PRIVILEGES ON *.* TO 'site_owner'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
